const morse = [
    { text: "A", code: ".-" },
    { text: "B", code: "-..." },
    { text: "C", code: "-.-." },
    { text: "D", code: "-.." },
    { text: "E", code: "." },
    { text: "F", code: "..-." },
    { text: "G", code: "--." },
    { text: "H", code: "...." },
    { text: "I", code: ".." },
    { text: "J", code: ".---" },
    { text: "K", code: "-.-" },
    { text: "L", code: ".-.." },
    { text: "M", code: "--" },
    { text: "N", code: "-." },
    { text: "O", code: "---" },
    { text: "P", code: ".--." },
    { text: "Q", code: "--.-" },
    { text: "R", code: ".-." },
    { text: "S", code: "..." },
    { text: "T", code: "-" },
    { text: "U", code: "..-" },
    { text: "V", code: "...-" },
    { text: "W", code: ".--" },
    { text: "X", code: "-..-" },
    { text: "Y", code: "-.--" },
    { text: "Z", code: "--.." },
    { text: "0", code: "-----" },
    { text: "1", code: ".----" },
    { text: "2", code: "..---" },
    { text: "3", code: "...--" },
    { text: "4", code: "....-" },
    { text: "5", code: "....." },
    { text: "6", code: "-...." },
    { text: "7", code: "--..." },
    { text: "8", code: "---.." },
    { text: "9", code: "----." }
]

export default morse